# Generated by Django 4.1.7 on 2023-05-08 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('firstTimeVisaApplication', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=20, null=True)),
                ('medicalCondition', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=20, null=True)),
                ('medicalConditionDescription', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('married', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=20, null=True)),
                ('religion', models.CharField(choices=[('Christian', 'Christian'), ('Muslim', 'Muslim'), ('Buddhist', 'Buddhist'), ('Atheist', 'Atheist'), ('Agnostic', 'Agnostic'), ('Other', 'Other')], default='Christian', max_length=20, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10, null=True)),
                ('academicPapers', models.FileField(null=True, upload_to='')),
                ('bankStatements', models.FileField(null=True, upload_to='')),
                ('resume', models.FileField(null=True, upload_to='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
