# Generated by Django 4.1.7 on 2023-05-25 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_candidatesapplied_rejected_candidatesapplied_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='Accomodation',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=20),
        ),
        migrations.AddField(
            model_name='school',
            name='institution',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='course',
            field=models.CharField(choices=[('Business', 'Business'), ('Information Technology', 'It'), ('Finance', 'Finance'), ('Education', 'Education'), ('Health', 'Health'), ('Telecommunication', 'Telecommunication'), ('Others', 'Others')], default='Business', max_length=30),
        ),
    ]
