# Generated by Django 4.2.3 on 2023-08-02 14:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_alter_school_tuitionfee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='tuitionFee',
            field=models.IntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000000)]),
        ),
    ]
