# Generated by Django 4.1.7 on 2023-05-25 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='industry',
            field=models.CharField(choices=[('Business', 'Business'), ('Information Technology', 'It'), ('Banking', 'Banking'), ('Education', 'Education'), ('Telecommunication', 'Telecommunication'), ('Transportation', 'Transportation'), ('Health', 'Health'), ('Engineering', 'Engineering'), ('Construction', 'Construction'), ('Others', 'Others')], default='Business', max_length=30),
        ),
    ]
